#!/usr/bin/env bash

DIRNAME="${BASH_SOURCE%[/\\]*}"
PID=0
# killall spacefn > /dev/null 2>&1

trap ctrl_c INT
ctrl_c() {
    echo -e "\nspacefn_forever: Trapped CTRL-C"
    # killall spacefn > /dev/null 2>&1
    kill -SIGTERM $PID
    exit
}

while true; do
  echo "==============================="
  echo "(RE)STARTED"

  ("$DIRNAME/spacefn" "$@")&
  PID=$!
  echo "PID: $PID"

  # echo "Wathing: $DIRNAME/spacefn"
  inotifywait "$DIRNAME/spacefn"

  # echo "Killing $PID"
  # killall spacefn > /dev/null 2>&1
  kill -SIGTERM $PID
  sleep 1
done
