#!/usr/bin/env bash

DIRNAME="${BASH_SOURCE%[/\\]*}"

trap ctrl_c INT
ctrl_c() {
    echo -e "\nspacefn_forever: Trapped CTRL-C"
    killall spacefn > /dev/null 2>&1
    exit
}

PID=0
killall spacefn > /dev/null 2>&1

while true; do
  echo "==============================="
  echo "(RE)STARTED"

  ./spacefn_lnx_apple.sh

  ("$DIRNAME/spacefn" "$1")&
  PID=$!
  echo "PID: $PID"

  # echo "Wathing: $DIRNAME/spacefn"
  inotifywait "$DIRNAME/spacefn"

  # echo "Killing $PID"
  # kill -SIGTERM $PID
  killall spacefn > /dev/null 2>&1
  sleep 1
done
