#!/usr/bin/env bash

DIRNAME="${BASH_SOURCE%[/\\]*}"

trap ctrl_c INT
ctrl_c() {
    echo "spacefn_forever: Trapped CTRL-C"
    exit
}

PID=0
killall spacefn > /dev/null 2>&1

while true; do
  "$DIRNAME"/spacefn "$1"
  PID=$!
  inotifywait "$DIRNAME"/spacefn
  kill -SIGTERM $PID
  sleep 1
done
