#!/usr/bin/sh

# Workaround for NixOS to find inotifywait when used as service
export PATH="/run/current-system/sw/bin/:$PATH"

SPACEFN="${BASH_SOURCE[0]}fn"
echo SpaceFn: $SPACEFN

echo "CLEANUP"
killall spacefn > /dev/null 2>&1

echo "SCANNING & STARTING"
ALL_KEYB=$(cat /proc/bus/input/devices | grep kbd | grep sysrq | grep -o "event\w*")
for EVENT in $ALL_KEYB; do
    echo "Starting $EVENT"
    $SPACEFN /dev/input/$EVENT &
done
sleep 5

echo "WATCHING"
while true; do
    STDOUT=$(inotifywait "/dev/input" -q -e CREATE)
    EVENT=$(echo $STDOUT | grep -o "event\w*")
    KEYB=$(cat /proc/bus/input/devices | grep kbd | grep sysrq | grep $EVENT)

    if [[ -z $KEYB ]]; then
        continue
    fi

    echo "$STDOUT"
    echo "Starting $EVENT"
    $SPACEFN /dev/input/$EVENT &
    sleep 1
done

