#!/usr/bin/env bash

while true; do
    killall spacefn > /dev/null 2>&1

    ALL_KEYB=$(cat /proc/bus/input/devices | grep kbd | grep sysrq | grep -o "event\w*")
    echo "ALL"
    for event in $ALL_KEYB; do
        echo $event
        ./spacefn /dev/input/$event &
    done

    ACT_KEYB=$(ps aux | grep "spacefn /dev/input" | grep -o "event\w*")
    echo -e "\nActive:"
    for event in $ACT_KEYB; do
        echo "* $event"
    done

    # Catch compile
    # inotifywait "./spacefn" -e ATTRIB #-e CLOSE

    inotifywait "/dev/input" -e CREATE -e DELETE
    sleep 1
done
